name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    concurrency:
      group: release
      cancel-in-progress: false

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - run: git reset --hard ${{ github.sha }}

      - uses: astral-sh/setup-uv@v6

      - uses: python-semantic-release/python-semantic-release@v10
        id: release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: github-actions
          git_committer_email: actions@users.noreply.github.com

      - uses: python-semantic-release/publish-action@v10
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
